package firewall

import (
	"fmt"
	"os"
	"strings"

	"github.com/filidorwiese/kekkai/internal/config"
)

// WriteConf renders the firewall conf and writes it to path. Format consumed
// by embed/init-firewall.sh.
func WriteConf(cfg *config.Config, path string) error {
	out := Render(cfg)
	return os.WriteFile(path, []byte(out), 0o644)
}

func Render(cfg *config.Config) string {
	var b strings.Builder
	b.WriteString("# generated by kekkai; do not edit\n")
	fmt.Fprintf(&b, "ALLOW_GITHUB_META=%s\n", boolToFlag(cfg.Firewall.AllowGithubMeta))
	fmt.Fprintf(&b, "ALLOW_HOST_LAN=%s\n", boolToFlag(cfg.Firewall.AllowHostLan))
	fmt.Fprintf(&b, "ALLOWED_DOMAINS=%q\n", strings.Join(cfg.Firewall.AllowedDomains, " "))
	return b.String()
}

func boolToFlag(b bool) string {
	if b {
		return "1"
	}
	return "0"
}
