package config

import (
	"bytes"
	"fmt"
	"os"
	"strings"

	kekkaiembed "github.com/filidorwiese/kekkai/embed"
	"gopkg.in/yaml.v3"
)

// ConfigBaseName is the config filename without extension; both .yml and .yaml are accepted.
const ConfigBaseName = ".kekkai"

// Load merges embedded defaults → ./.kekkai.{yml,yaml}.
// projectDir is typically the current working directory; home is used to expand
// ~ in the merged result.
func Load(home string, projectDir string) (*Config, error) {
	cfg, err := decodeDefaults()
	if err != nil {
		return nil, fmt.Errorf("decode embedded defaults: %w", err)
	}

	projectPath, err := resolveConfigPath(projectDir)
	if err != nil {
		return nil, err
	}
	if err := mergeFile(cfg, projectPath); err != nil {
		return nil, err
	}

	cfg.Env = dedupEnv(cfg.Env)
	cfg.Image.AptPackages = dedupStrings(cfg.Image.AptPackages)
	cfg.Firewall.AllowedDomains = dedupStrings(cfg.Firewall.AllowedDomains)

	if err := Expand(cfg, home); err != nil {
		return nil, err
	}
	cfg.Mounts = dedupMounts(cfg.Mounts)
	if err := Validate(cfg); err != nil {
		return nil, err
	}
	return cfg, nil
}

// YAML renders cfg as a complete, valid .kekkai.yaml document — every key with
// its merged, expanded value. Suitable for `kekkai config --yaml > ./.kekkai.yaml`
// to snapshot the current configuration as a starting point.
func YAML(cfg *Config) ([]byte, error) {
	body, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, err
	}
	header := "# kekkai configuration snapshot (merged defaults + ./.kekkai.yaml)\n" +
		"# generated by `kekkai config --yaml`\n"
	return append([]byte(header), body...), nil
}

// Source returns the project config file path that Load merges on top of the
// embedded defaults. An empty string means no file was found. It surfaces the
// same ambiguity error as Load (both extensions present).
func Source(projectDir string) (project string, err error) {
	return resolveConfigPath(projectDir)
}

// resolveConfigPath probes dir for .kekkai.yml and .kekkai.yaml. It returns the
// existing one, "" if neither exists, or an error if both exist (ambiguous).
func resolveConfigPath(dir string) (string, error) {
	ymlPath := dir + "/" + ConfigBaseName + ".yml"
	yamlPath := dir + "/" + ConfigBaseName + ".yaml"
	ymlOK := fileExists(ymlPath)
	yamlOK := fileExists(yamlPath)
	switch {
	case ymlOK && yamlOK:
		return "", fmt.Errorf("both %s and %s exist; keep only one", ymlPath, yamlPath)
	case ymlOK:
		return ymlPath, nil
	case yamlOK:
		return yamlPath, nil
	default:
		return "", nil
	}
}

func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}

// dedupEnv keeps only the last occurrence of each KEY in a list of KEY=value
// entries, so later layers override earlier ones per key. Order follows each
// key's final position.
func dedupEnv(entries []string) []string {
	last := map[string]int{}
	for i, e := range entries {
		last[envKey(e)] = i
	}
	out := make([]string, 0, len(entries))
	for i, e := range entries {
		if last[envKey(e)] == i {
			out = append(out, e)
		}
	}
	return out
}

// dedupStrings drops duplicate entries, keeping the first occurrence and order.
// Keeps append-only arrays (apt_packages, allowed_domains) idempotent under
// re-merge so a `kekkai config --yaml` snapshot round-trips cleanly.
func dedupStrings(in []string) []string {
	seen := make(map[string]bool, len(in))
	out := make([]string, 0, len(in))
	for _, s := range in {
		if seen[s] {
			continue
		}
		seen[s] = true
		out = append(out, s)
	}
	return out
}

// dedupMounts drops mounts that are fully identical to a later entry, keeping the
// last. This makes re-merging an already-complete config (e.g. the output of
// `kekkai config --yaml`) idempotent. Runs after Expand so defaults and snapshot
// compare on resolved paths. Genuine conflicts (same target, different source)
// are left for Validate to reject.
func dedupMounts(mounts []Mount) []Mount {
	type key struct {
		source, target     string
		readonly, optional bool
	}
	k := func(m Mount) key { return key{m.Source, m.Target, m.Readonly, m.Optional} }
	last := map[key]int{}
	for i, m := range mounts {
		last[k(m)] = i
	}
	out := make([]Mount, 0, len(mounts))
	for i, m := range mounts {
		if last[k(m)] == i {
			out = append(out, m)
		}
	}
	return out
}

func envKey(e string) string {
	if i := strings.IndexByte(e, '='); i >= 0 {
		return e[:i]
	}
	return e
}

func decodeDefaults() (*Config, error) {
	var cfg Config
	dec := yaml.NewDecoder(bytes.NewReader(kekkaiembed.DefaultsYAML))
	dec.KnownFields(true)
	if err := dec.Decode(&cfg); err != nil {
		return nil, err
	}
	return &cfg, nil
}

func mergeFile(cfg *Config, path string) error {
	if path == "" {
		return nil
	}
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("open %s: %w", path, err)
	}
	defer f.Close()

	var l layer
	dec := yaml.NewDecoder(f)
	dec.KnownFields(true)
	if err := dec.Decode(&l); err != nil {
		return fmt.Errorf("parse %s: %w", path, err)
	}
	mergeLayer(cfg, &l)
	return nil
}

func mergeLayer(cfg *Config, l *layer) {
	if l.Image != nil {
		if l.Image.Base != nil {
			cfg.Image.Base = *l.Image.Base
		}
		if l.Image.ClaudeCodeVersion != nil {
			cfg.Image.ClaudeCodeVersion = *l.Image.ClaudeCodeVersion
		}
		if l.Image.DockerCliVersion != nil {
			cfg.Image.DockerCliVersion = *l.Image.DockerCliVersion
		}
		cfg.Image.AptPackages = append(cfg.Image.AptPackages, l.Image.AptPackages...)
	}
	cfg.Mounts = append(cfg.Mounts, l.Mounts...)
	cfg.Env = append(cfg.Env, l.Env...)
	if l.Firewall != nil {
		if l.Firewall.AllowHostLan != nil {
			cfg.Firewall.AllowHostLan = *l.Firewall.AllowHostLan
		}
		cfg.Firewall.AllowedDomains = append(cfg.Firewall.AllowedDomains, l.Firewall.AllowedDomains...)
	}
	if l.Claude != nil && l.Claude.Args != nil {
		cfg.Claude.Args = *l.Claude.Args
	}
	if l.DockerAccess != nil {
		cfg.DockerAccess = *l.DockerAccess
	}
}
